INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Camp Nou','Cataluna','1957','99354');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Santiago Bernabeu','Comunidad de Madrid','1947','81044');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Metropolitano','Comunidad de Madrid','2017','67703');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Benito Villamarin','Andalucia','1929','60721');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Cartuja','Andalucia','1997','60000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Olimpico Lluis Companys','Cataluna','1927','55926');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Mestalla','Comunidad Valenciana','1923','55000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('San Mames','Pais Vasco','2013','53289');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ramon Sanchez Pizjuan','Andalucia','1958','43883');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Anoeta','Pais Vasco','1993','42000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('RCDE Stadium','Cataluna','2009','40500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Manuel Martinez Valero','Comunidad Valenciana','1976','33732');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Romareda','Aragon','1957','33608');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Riazor','Galicia','1944','32911');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Gran Canaria','Canarias','2003','32392');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nueva Condomina','Region de Murcia','2006','31179');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Balaidos','Galicia','1928','31100');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Carlos Tartiere','Principado de Asturias','2000','30500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Rosaleda','Andalucia','1941','30044');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Molinon','Principado de Asturias','1908','30000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Jose Rico Perez','Comunidad Valenciana','1974','29500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Jose Zorrilla','Castilla y Leon','1982','26512');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ciudad de Valencia','Comunidad Valenciana','1969','25354');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ramon de Carranza','Andalucia','1957','25033');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Son Moix','Islas Baleares','1999','24262');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Estadio de la Ceramica','Comunidad Valenciana','1923','23500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Heliodoro Rodriguez Lopez','Canarias','1925','23000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nuevo Los Carmenes','Andalucia','1995','22369');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Sardinero','Cantabria','1988','22222');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nuevo Arcangel','Andalucia','1993','21822');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nuevo Colombino','Andalucia','2001','21670');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Chapin','Andalucia','1988','20486');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Mendizorroza','Pais Vasco','1924','19840');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Sadar','Navarra','1967','19800');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Balear','Islas Baleares','1960','18000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Carlos Belmonte','Castilla-La Mancha','1960','18000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Helmantico','Castilla y Leon','1970','17341');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Coliseum Alfonso Perez','Comunidad de Madrid','1998','17000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Las Gaunas','La Rioja','2002','16000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nuevo Vivero','Extremadura','1998','15598');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Castalia','Comunidad Valenciana','1987','15500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Mini Estadi','Cataluna','1982','15276');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Cartagonova','Region de Murcia','1988','15105');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Juegos Mediterraneos','Andalucia','2004','15000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Estadio de Vallecas','Comunidad de Madrid','1976','14708');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Romano','Extremadura','1953','14537');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nou Estadi de Tarragona','Cataluna','1971','14500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Soto','Comunidad de Madrid','1974','14000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Camp d Esports','Cataluna','1919','13500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Reino de Leon','Castilla y Leon','2001','13451');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal de Montilivi','Cataluna','1970','13400');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Juan Rojas','Andalucia','1976','13000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('San Lazaro','Galicia','1993','13000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Victoria','Andalucia','2001','12600');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Butarque','Comunidad de Madrid','1998','12450');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Plantio','Castilla y Leon','1964','12200');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('A Malata','Galicia','1993','12043');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Pasaron','Galicia','1956','12000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nova Creu Alta','Cataluna','1967','11981');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Francisco de la Hera','Extremadura','1951','11580');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Olimpic de Terrassa','Cataluna','1960','11500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ciudad de Tudela','Navarra','1969','11000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ciudad de Malaga','Andalucia','2006','10816');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Alvarez Claro','Melilla','1945','10000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Linarejos','Andalucia','1956','10000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nou Camp de Inca','Islas Baleares','1964','10000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal de Vilatenim','Cataluna','1986','9472');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nuevo Los Pajaritos','Castilla y Leon','1999','9025');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Murta','Comunidad Valenciana','1920','9000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Guillermo Amor','Comunidad Valenciana','1964','9000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Antonio Peroles','Andalucia','2005','9000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Jose del Cuvillo','Andalucia','1972','8600');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Toralin','Castilla y Leon','2000','8200');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ipurua','Pais Vasco','1947','8127');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Francisco Artes Carrasco','Region de Murcia','2003','8120');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Luis Suner','Comunidad Valenciana','1973','8100');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nueva Balastera','Castilla y Leon','2006','8070');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Francisco Peraza','Canarias','1923','8000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal El Val','Comunidad de Madrid','1947','8000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Pepico Amat','Comunidad Valenciana','1964','8000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Gerardo Salvador','Comunidad Valenciana','1971','8000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Viejo Nervion','Andalucia','1974','8000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nou Camp de Sa Pobla','Islas Baleares','1977','8000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal de San Miguel','Andalucia','1986','8000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Iberoamericano 2010','Andalucia','1992','8000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ciudad de Puertollano','Castilla-La Mancha','2010','8000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Lasesarre','Pais Vasco','2001','7960');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Angel Carro','Galicia','1974','7840');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ruta de la Plata','Castilla y Leon','2002','7813');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Alcoraz','Aragon','1972','7638');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Antonio Dominguez Alfonso','Canarias','1992','7500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nuevo Mirador','Andalucia','1999','7200');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ciudad Deportiva de Lanzarote','Canarias','1968','7000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal de Marbella','Andalucia','1975','7000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Principe Felipe','Extremadura','1977','7000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Narcis Sala','Cataluna','1970','6593');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Alfonso Murube','Ceuta','1933','6500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal Villanovense','Extremadura','1992','6500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Estadi de la Feixa Llarga','Cataluna','1999','6294');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nuevo Malecon','Cantabria','1922','6007');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Guadalquivir','Andalucia','1923','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Pedro Escartin','Castilla-La Mancha','1967','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Vicente Garcia','Comunidad Valenciana','1971','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Albuera','Castilla y Leon','1977','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Alfredo Di Stefano','Comunidad de Madrid','2005','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Fuensanta','Castilla-La Mancha','2011','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Prado','Castilla-La Mancha','1944','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Planilla','La Rioja','1946','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Anduva','Castilla y Leon','1950','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Alberto Fernandez','Castilla y Leon','1968','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Adolfo Suarez','Castilla y Leon','1976','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Montecillo','Castilla y Leon','1977','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('San Pablo','Andalucia','1986','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nou Municipal de Palamos','Cataluna','1989','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ciutat Esportiva Dani Jarque','Cataluna','2001','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Virgen de las Nieves','Canarias','2001','6000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('O Couto','Galicia','1948','5659');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Magdalena','Comunidad Valenciana','1949','5500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Arboleja','Murcia','1984','5500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nuevo Roman Suarez Puerta','Principado de Asturias','1999','5500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nuestra Senora de la Caridad','Castilla-La Mancha','1958','5500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Chamorro Martinez','Andalucia','1970','5500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Polideportivo Municipal','Castilla-La Mancha','1976','5500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ciudad Deportiva de Plasencia','Extremadura','1982','5500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Los Corrales','Cantabria','2013','5500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Salto del Caballo','Castilla-La Mancha','1973','5300');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ciudad de Ayamonte','Andalucia','2007','5200');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Santo Domingo','Comunidad de Madrid','1978','5100');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ciudad Deportiva del Villarreal CF','Comunidad Valenciana','2002','5100');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Vicente Sanz','Extremadura','1957','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal de Lucena','Andalucia','1972','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Mauli','Andalucia','1981','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Serratella','Comunidad Valenciana','2000','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Stadium Gal','Pais Vasco','1926','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Constitucion','Region de Murcia','1944','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Palmar','Andalucia','1948','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal de Tomelloso','Castilla-La Mancha','1948','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Clariano','Comunidad Valenciana','1951','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Miramar','Principado de Asturias','1952','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Los Cuartos','Canarias','1953','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Pinilla','Aragon','1957','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal de Deportes','Aragon','1966','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Escribano Castilla','Andalucia','1970','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nuevo Estadio','Extremadura','1972','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal Navalmoral de la Mata','Extremadura','1972','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nuevo Silvestre Carrillo','Canarias','1977','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Camp Nou Municipal','Cataluna','1978','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal de Montilla','Andalucia','1981','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Mundial 82','Comunidad Valenciana','1984','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nou Municipal','Cataluna','1994','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Bòbila','Cataluna','1995','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Juventud','Andalucia','2001','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Artunduaga','Pais Vasco','2007','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ciudad Deportiva Municipal','Extremadura','2007','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal de Alcazar','Castilla-La Mancha','','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Baltar','Galicia','','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Orellana','Principado de Asturias','','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Gazituaga','Pais Vasco','','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Fernando Torres','Comunidad de Madrid','','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal','Canarias','','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Ciudad Deportiva','Extremadura','','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Manuel Calzado Galvan','Extremadura','','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Santa Ana','Aragon','','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Isidro Calderon','Aragon','','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Olivar','Castilla-La Mancha','','5000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Condomina','Region de Murcia','1924','4600');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Area Deportiva de Puente Castro','Castilla y Leon','1998','4600');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Estadi Municipal de Can Misses','Islas Baleares','1991','4500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Matias Prats','Andalucia','1934','4500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Las Llanas','Pais Vasco','1923','4367');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Mazo','La Rioja','2004','4300');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal de Badalona','Cataluna','2017','4170');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Hermanos Antuna','Principado de Asturias','1951','4000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nou Sardenya','Cataluna','1995','4000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Rubial','Region de Murcia','1913','4000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Estadio El Carmen Sarinena','Aragon','1960','4000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Merkatondoa','Navarra','1928','3500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Los Arcos','Comunidad Valenciana','1945','3500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('As Eiroas','Galicia','2001','3500');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Cerro del Espino​','Comunidad de Madrid','1995','3376');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Guillermo Olagüe','Comunidad Valenciana','1967','3259');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('El Pilar','Cantabria','1922','3000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Pepe Ortiz','Principado de Asturias','1995','3000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Pepe Goncalvez','Canarias','1938','3000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Javier Sotomayor','Castilla y Leon','1970','2400');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal de Ejea','Aragon','2010','2223');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Mina','Comunidad de Madrid','1916','2000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('La Espiguera','Melilla','1917','2000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Municipal de Guijuelo','Castilla y Leon','1970','2000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Nuevo San Bartolome','Andalucia','1982','2000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Vicente del Bosque','Castilla y Leon','2013','2000');
INSERT INTO Estadio (Nom_estadio,Comunidad,Inaguracion,Capacidad) VALUES ('Desconocido','Desconocido','0','0');