INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Nuevo Colombino','Rec. Huelva');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Ramon Sanchez-Pizjuan','Sevilla');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('San Mames','Ath. Bilbao');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Camp Nou','Barcelona');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('RCDE Stadium','Espanyol');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Santiago Bernabeu','Real Madrid');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Nova Creu Alta','Sabadell');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Municipal de Badalona','Badalona');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Estadio Metropolitano','At. Madrid');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Suarez Puerta','Aviles');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Villafranca');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Municipal El Molinon','Sporting Gijon');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Besain');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Santfeliuenc');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('La Mina','Carabanchel');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Riazor','Dptivo. Coruna');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Nou Sardenya','Europa');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Benito Villamarin','Betis');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('El Malecon','Torrelavega');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Nueva Condomina','Murcia');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Municipal de Anoeta','Real Sociedad');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Portugalete');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Ciudad de Valencia','Levante');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Camp Nou Municipal','Reus');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Getxo');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Nuevo Mirador','Algeciras');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Ramon de Carranza','Cadiz');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Luarca');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Les Tolves','Titanico');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Municipal','Linense');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Icodense');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Garachico');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Heliodoro Rodriguez Lopez','Tenerife');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('El Sardinero','Rac. Santander');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Artunduaga','Basconia');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Deusto');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('El Mazo','Haro');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Dptivo. Coruna B');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Nou Estadi','Gimn. Tarragona');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Jose Rico Perez','Hercules');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Cayon');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','R.U. Tenerife');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Stadium Gal','Real Union');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Erandio');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Siero');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Lealtad');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Son Moix','Mallorca');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Contestano');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Pumarin');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('La Cueva','Pilonesa');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Lasesarre','Barakaldo');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Elgoibar');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Hermanos Antuna','Caudal');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Santutxu');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Durango');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Lutxana');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Acero');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Cartagonova','Cartagena F.C.');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Municipal de Vilatenim','Figueres');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Principe Felipe','Cacereno');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Mestalla','Valencia');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('A Malata','Ferrol');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Balear','At. Baleares');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Capellades');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('El Sadar','Osasuna');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Pepico Amat','Eldense');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Mendizorroza','Alaves');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Castalia','Castellon');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('El Toralin','Ponferradina');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Martinez Valero','Elche');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Virgen de las Nieves','Tenisca');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Nuevo Silvestre Carrillo','Mensajero');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Tolosa');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Velez');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Gernika');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Astur');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Municipal Reino de Leon','Cult. Leonesa');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Balaidos','Celta');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Campo de Futbol de Vallecas','Rayo Vallecano');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Merkatondoa','Izarra');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Narcis Sala','Sant Andreu');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Amorebieta');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Carlos Tartiere','Oviedo');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Municipal de Anduva','Mirandes');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Jose Zorrilla','Valladolid');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Municipal de Butarque','Leganes');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('El Collao','Alcoyano');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Carrion');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Jose del Cuvillo','Portuense');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Calavera');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('La Victoria','Jaen');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Oviedo Vetusta');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Municipal de Montilivi','Girona');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Alfredo Di Stefano','Real Madrid B');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Nuevo Los Carmenes','Granada');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Puerto Real');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Miramar','Luanco');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('La Romareda','Zaragoza');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Antonio Dominguez Alfonso','Marino');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Carlos Belmonte','Albacete');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Pasaron','Pontevedra');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Ipurua','Eibar');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Paterna','Valencia B');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Nuevo Los Pajaritos','Numancia');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Estadio de la Ceramica','Villarreal');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Municipal de Chapin','Xerez');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Pedro Escartin','Guadalajara');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Miguel Prieto','Granada B');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Ciudad de Puertollano','Puertollano');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('La Rosaleda','Malaga (C.D.)');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Gran Canaria','Las Palmas');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Viejo Nervion','Sevilla B');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Anxo Carro','Lugo');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Nuevo Arcangel','Cordoba');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Nou Estadi de Palamos','Palamos');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Alfonso Murube','Ceuta');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('El Alcoraz','Huesca');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Langreo');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Cerro del Espino','At. Madrid B');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Ath. Bilbao B');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Las Gaunas','Logrones (U.D.)');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Mini Estadi','Barcelona B');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Santo Domingo','Alcorcon');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Municipal de Montilla','Montilla');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Cerro del Espino','Rayo Majadahonda');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Alboraya');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Coliseum Alfonso Perez','Getafe');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Getafe B');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Burgos (Real)');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Juegos Mediterraneos','Almeria');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Municipal de El Plantio','Burgos (C.F.)');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Cartagonova','Cartagena');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Las Llanas','Sestao River');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Alcorcon B');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('La Condomina','UCAM Murcia');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Multiusos de San Lazaro','Compos');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Francisco de la Hera','Extremadura (U.D.)');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Las Gaunas','Logrones (S.D.)');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Olimpic de Terrassa','Tarrasa Olimpica');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Camp d Esports','Lleida Espiritu');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Nuevo Vivero','Badajoz (C.D.)');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Municipal de Chapin','Xerez (F.C.)');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Unionistas');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Romano','Merida (A.D.)');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Exiles');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Rio Tinto');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Cricket y Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Malaga English Clubn 7');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Athleta Club de Astilleros del Nervion');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Foot-Ball Club Barcelona');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Gran Canary Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Las Palmas Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Asociacion de Football de Torello');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Veloz Sport Balear');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Sociedad de Juegos al Aire Libre');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','New Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Association Sportive Amicale');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Palamos Club de Futbol');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Català Sport Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Hispania Athletic Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Campo de Lamiaco','Bilbao Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Expda. de la Pza. de Toros','Club Espanol de Madrid *');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Campo de Moncloa','Moncloa Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Retiro Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Campo del Hipodromo','Moderno Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Explanada de El Bibio','Gijon Sport Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Hispania Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Victoria Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Union Vizcaina');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Universidad de Deusto Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Iberia Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Sport Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Internacional Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Boston Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Nacional Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Vizcaya Foot-Ball Clubn 8');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Hispania Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Malaga Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Club Foot-Ball Segoviano');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Asociacion Asturiana de Foot-Ball');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Zaragoza Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Oviedo Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Vigo Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Real Club Coruna');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Juventud Deportiva Gijonesa');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Sport Club Avilesino');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Sporting Club Lucentino');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','San Sebastian Recreation Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Club Gimnastico');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Club Deportivo Gran Canaria');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Nuevo Vivero','Badajoz');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','New Sporting Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Real Club Fortuna de Vigo');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Foot-Ball Club Valencia');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Iris Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Club Sportivo Internacional');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Espanol Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Olimpico de Tarrasa','Terrasa');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Real Sociedad Gimnastica Espanola');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Xerez Futbol Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','San Sebastian Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Alicante Recreation Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Gimnastico Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Foot-Ball Club Cabanal');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Espanol Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Sporting Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Real Vigo Sporting Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Foot-Ball Club Malagueno');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Club Deportivo Norte');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Union Sporting Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Club Nuevo Fomento Oriental');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Racing Club de Madrid');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Sestao');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Iberia');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Alicante');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','A.D. Ferroviaria');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Romano','Merida');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Las Gaunas','Logrono');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('El Plantio','Burgos');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Imperio');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Helmantico','Salamanca');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Estadio de la Ceramica','Villarreal E y D');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Nacional de Madrid');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Francisco de la Hera','Extremadura');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Getafe Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Zaragoza Club Deportivo');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Compostela Club de Futbol');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Real Club Deportivo Cordoba');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Castilla Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('La Rosaleda','Club Deportivo Malaga');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Club Deportivo Condal');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Camp d Esports','Lleida');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Estadio Las Gaunas','Logrones');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Riazor','Club Deportivo Juvenil');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Desconocido','Eibar Foot-Ball Club');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Club Getafe Deportivo');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('O Couto','Ourense');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Madrid C');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Multiusos de San Lazaro','Compostela');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Mini Estadi','Barcelona C');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Santo Domingo','Ejido');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Almeria (A.D.)');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Romano','Merida');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('Francisco Artes Carrasco','Lorca');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Granada 74');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Real Stadium Club Ovetense');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Real Club Deportivo Oviedo');
INSERT INTO Tener (Nom_equip,Nom_estadio) VALUES ('','Club Deportivo Espanol');