INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Club Recreativo de Huelva;Huelva;1889;Rec. Huelva');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sevilla Futbol Club;Sevilla;1890;Sevilla');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Athletic Club;Bilbao;1898;Ath. Bilbao');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Futbol Club Barcelona;Barcelona;1899;Barcelona');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Club Deportivo Espanol;Barcelona;1900;Espanyol');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Madrid Club de Futbol;Madrid;1900;Real Madrid');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Centre d Esports Sabadell Futbol Club;Sabadell;1901;Sabadell');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club de Futbol Badalona;Badalona;1903;Badalona');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Atletico de Madrid;Madrid;1903;At. Madrid');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Aviles Club de Futbol;Aviles;1903;Aviles');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Futbol Club Vilafranca;Vilafranca del Penedès;1904;Villafranca');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Sporting de Gijon;Gijon;1905;Sporting Gijon');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sociedad Deportiva Beasain;Beasain;1905;Besain');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Santfeliuenc Futbol Club;Sant Feliu de Llobregat;1905;Santfeliuenc');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Club Deportivo Carabanchel;Madrid;1906;Carabanchel');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Club Deportivo de La Coruna;La Coruna;1906;Dptivo. Coruna');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Esportiu Europa;Barcelona;1907;Europa');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Betis Balompie;Sevilla;1907;Betis');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Gimnastica de Torrelavega;Torrelavega;1907;Torrelavega');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Murcia Club de Futbol;Murcia;1908;Murcia');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Sociedad de Futbol;San Sebastian;1909;Real Sociedad');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Portugalete;Portugalete;1909;Portugalete');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Levante Union Deportiva;Valencia;1909;Levante');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club de Futbol Reus Deportiu;Reus;1909;Reus');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Arenas Club de Guecho;Guecho;1909;Getxo');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Algeciras Club de Futbol;Algeciras;1909;Algeciras');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Cadiz Club de Futbol;Cadiz;1910;Cadiz');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Luarca Club de Futbol;Luarca;1912;Luarca');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Titanico;Pola de Laviana;1912;Titanico');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Balompedica Linense;La Linea;1912;Linense');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Union Deportiva Icodense;Tenerife;1912;Icodense');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Club Deportivo Gara;Garachico;1912;Garachico');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Tenerife;Santa Cruz de Tenerife;1912;Tenerife');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Racing Club de Santander;Santander;1913;Rac. Santander');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Basconia;Basauri;1913;Basconia');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sociedad Deportiva Deusto;Deusto;1913;Deusto');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Haro Deportivo;Haro;1914;Haro');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('" Real Club Deportivo de La Coruna ""B""";La Coruna;1914;Dptivo. Coruna B');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Gimnàstic de Tarragona;Tarragona;1914;Gimn. Tarragona');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Hercules de Alicante Club de Futbol;Alicante;1914;Hercules');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Cayon;Santa Maria de Cayon;1915;Cayon');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Union de Tenerife Club de Futbol;Tenerife;1915;R.U. Tenerife');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Union Club;Irun;1915;Real Union');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sociedad Deportiva Erandio Club;Erandio;1915;Erandio');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Siero;Pola de Siero;1916;Siero');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Lealtad;Villaviciosa;1916;Lealtad');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Club Deportivo Mallorca;Palma de Mallorca;1916;Mallorca');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Contestano;Cocentaina;1917;Contestano');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Pumarin Club de Futbol;Oviedo;1917;Pumarin');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Deportiva Pilonesa;Infiesto;1917;Pilonesa');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Barakaldo Club de Futbol;Baracaldo;1917;Barakaldo');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Elgoibar;Elgoibar;1917;Elgoibar');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Caudal Deportivo;Mieres;1918;Caudal');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Santutxu Futbol Club;Santutxu;1918;Santutxu');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sociedad Cultural Deportiva de Durango;Durango;1919;Durango');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sporting Club de Lutxana;Baracaldo;1919;Lutxana');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Acero;Puerto de Sagunto;1919;Acero');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Cartagena Futbol Club;Cartagena;1919;Cartagena F.C.');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Unio Esportiva Figueres;Figueras;1919;Figueres');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Polideportivo Cacereno;Caceres;1919;Cacereno');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Valencia Club de Futbol;Valencia;1919;Valencia');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Racing Club de Ferrol;Ferrol;1919;Ferrol');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Atletico Baleares;Palma de Mallorca;1920;At. Baleares');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Futbol Capellades;Capellades;1920;Capellades');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Atletico Osasuna;Pamplona;1920;Osasuna');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Eldense;Elda;1921;Eldense');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Deportivo Alaves;Vitoria;1921;Alaves');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Castellon;Castellon de la Plana;1919;Castellon');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sociedad Deportiva Ponferradina;Ponferrada;1921;Ponferradina');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Elche Club de Futbol;Elche;1922;Elche');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sociedad Deportiva Tenisca;Santa Cruz de La Palma;1922;Tenisca');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Mensajero;Santa Cruz de La Palma;1922;Mensajero');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Tolosa Club de Futbol;Tolosa;1922;Tolosa');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Velez Club de Futbol;Velez-Malaga;1922;Velez');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sociedad Deportiva Gernika Club;Gernika;1922;Gernika');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Astur Club de Futbol;Oviedo;1923;Astur');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Cultural y Deportiva Leonesa;Leon;1923;Cult. Leonesa');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Club Celta de Vigo;Vigo;1923;Celta');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Rayo Vallecano de Madrid;Madrid;1924;Rayo Vallecano');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Izarra;Estella;1924;Izarra');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Unio Esportiva Sant Andreu;Barcelona;1925;Sant Andreu');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sociedad Deportiva Amorebieta;Vizcaya;1925;Amorebieta');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Oviedo;Oviedo;1926;Oviedo');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Mirandes;Miranda de Ebro;1927;Mirandes');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Valladolid Club de Futbol;Valladolid;1928;Valladolid');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Leganes;Leganes;1928;Leganes');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Alcoyano;Alcoy;1928;Alcoyano');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Carrion Balompie;Carrion de los Cespedes;1928;Carrion');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Racing Club Portuense;El Puerto de Santa Maria;1928;Portuense');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Calavera Club de Futbol;Sevilla;1928;Calavera');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Jaen Club de Futbol;Jaen;1929;Jaen');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Oviedo Vetusta;Oviedo;1930;Oviedo Vetusta');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Girona Futbol Club;Gerona;1930;Girona');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Madrid Castilla Club de Futbol;Madrid;1930;Real Madrid B');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Granada Club de Futbol;Granada;1931;Granada');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Puerto Real Club de Futbol;Puerto Real;1931;Puerto Real');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Marino de Luanco;Luanco;1931;Luanco');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Zaragoza;Zaragoza;1932;Zaragoza');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Marino;Arona;1933;Marino');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Albacete Balompie;Albacete;1940;Albacete');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Pontevedra Club de Futbol;Pontevedra;1941;Pontevedra');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sociedad Deportiva Eibar;eibar;1943;eibar');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Valencia Club de Futbol Mestalla;Paterna;1944;Valencia B');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Numancia de Soria;Soria;1945;Numancia');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Villarreal Club de Futbol;Villarreal;1944;Villarreal');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Xerez Club Deportivo;Jerez de la Frontera;1947;Xerez');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Guadalajara;Guadalajara;1947;Guadalajara');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Recreativo Granada;Granada;1947;Granada B');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Puertollano;Puertollano;1948;Puertollano');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Malaga Club de Futbol;Malaga;1948;Malaga (C.D.)');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Union Deportiva Las Palmas;Las Palmas;1949;Las Palmas');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sevilla Atletico Club;Sevilla;1950;Sevilla B');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Lugo;Lugo;1953;Lugo');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Cordoba Club de Futbol;Cordoba;1954;Cordoba');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Palamos Club de Futbol;Palamos;1954;Palamos');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Atletico de Ceuta;Ceuta;1956;Ceuta');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sociedad Deportiva Huesca;Huesca;1960;Huesca');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Union Popular de Langreo;Langreo;1961;Langreo');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('" Club Atletico de Madrid ""B""";Majadahonda;1963;At. Madrid B');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Bilbao Athletic;Lezama;1964;Ath. Bilbao B');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Union Deportiva Logrones;Logrono;1967;Logrones (U.D.)');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('" Futbol Club Barcelona ""B""";Barcelona;1970;Barcelona B');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Agrupacion Deportiva Alcorcon;Alcorcon;1971;Alcorcon');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Montilla Club de Futbol;Montilla;1973;Montilla');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club de Futbol Rayo Majadahonda;Majadahonda;1976;Rayo Majadahonda');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Alboraya Union Deportiva;Alboraya;1978;Alboraya');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Getafe Club de Futbol;Getafe;1983;Getafe');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('" Getafe Club de Futbol ""B""";Getafe;1983;Getafe B');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Burgos Club de Futbol;Burgos;1983;Burgos (Real)');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Union Deportiva Almeria;Almeria;1989;Almeria');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Burgos Club de Futbol;Burgos;1994;Burgos (C.F.)');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Futbol Club Cartagena;Cartagena;1995;Cartagena');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sestao River Club;Sestao;1996;Sestao River');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('" Agrupacion Deportiva Alcorcon ""B""";Alcorcon;1998;Alcorcon B');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('UCAM Murcia Club de Futbol;Murcia;1999;UCAM Murcia');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sociedad Deportiva Compostela;Santiago de Compostela;2004;Compos');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Extremadura Union Deportiva;Almendralejo;2007;Extremadura (U.D.)');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sociedad Deportiva Logrones;Logrono;2009;Logrones (S.D.)');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Tarrasa Olimpica 2010;Tarrasa;2009;Tarrasa Olimpica');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Lleida Esportiu;Lerida;2011;Lleida Espiritu');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Badajoz;Badajoz;2012;Badajoz (C.D.)');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Xerez Deportivo Futbol Club;Jerez de la Frontera;2013;Xerez (F.C.)');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Unionistas de Salamanca Club de Futbol;Salamanca;2013;Unionistas');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Merida Asociacion Deportiva;Merida;2013;Merida (A.D.)');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Exiles Foot-Ball Club;Vigo;1876;Exiles');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Rio Tinto Foot-Ball Clubn 6;Huelva;1878;Rio Tinto');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Cricket y Foot-Ball Club;Madrid;1879; Cricket y Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Malaga English Clubn 7;Malaga;1890; Malaga English Clubn 7');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Athleta Club de Astilleros del Nervion;Bilbao;1891; Athleta Club de Astilleros del Nervion');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Foot-Ball Club Barcelona;Barcelona;1893; Foot-Ball Club Barcelona');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Gran Canary Foot-Ball Club;Las Palmas;1894; Gran Canary Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Las Palmas Foot-Ball Club;Puerto de Las Palmas;1894; Las Palmas Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Asociacion de Football de Torello;Barcelona;1894; Asociacion de Football de Torello');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Veloz Sport Balear;Palma de Mallorca;1896; Veloz Sport Balear');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sociedad de Juegos al Aire Libre;Madrid;1897; Sociedad de Juegos al Aire Libre');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('New Foot-Ball Club;Madrid;1897; New Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Association Sportive Amicale;Madrid;1897; Association Sportive Amicale');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Palamos Club de Futbol;Palamos;1898; Palamos Club de Futbol');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Català Sport Club;Barcelona;1899; Català Sport Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Hispania Athletic Club;Barcelona;1900; Hispania Athletic Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Bilbao Foot-Ball Club;Bilbao;1900; Bilbao Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Espanol de Madrid *;Madrid;1901; Club Espanol de Madrid *');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Moncloa Foot-Ball Club;Madrid;1902; Moncloa Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Retiro Foot-Ball Club;Madrid;1902; Retiro Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Moderno Foot-Ball Club;Madrid;1902; Moderno Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Gijon Sport Club;Gijon;1902; Gijon Sport Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Hispania Foot-Ball Club;Madrid;1902; Hispania Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Victoria Foot-Ball Club;Madrid;1902; Victoria Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Union Vizcaina;Bilbao;1902; Union Vizcaina');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Universidad de Deusto Foot-Ball Club;Bilbao;1902; Universidad de Deusto Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Iberia Foot-Ball Club;Madrid;1903; Iberia Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sport Foot-Ball Club;Madrid;1903; Sport Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Internacional Foot-Ball Club;Madrid;1903; Internacional Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Boston Foot-Ball Club;Madrid;1903; Boston Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Nacional Foot-Ball Club;Madrid;1903; Nacional Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Vizcaya Foot-Ball Clubn 8;Madrid;1903; Vizcaya Foot-Ball Clubn 8');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Hispania Foot-Ball Club;Bilbao;1903; Hispania Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Malaga Foot-Ball Club;Malaga;1903; Malaga Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Foot-Ball Segoviano;Segovia;1903; Club Foot-Ball Segoviano');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Asociacion Asturiana de Foot-Ball;Madrid;1903; Asociacion Asturiana de Foot-Ball');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Zaragoza Foot-Ball Club;Zaragoza;1903; Zaragoza Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Oviedo Foot-Ball Club;Oviedo;1903; Oviedo Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Vigo Foot-Ball Club;Vigo;1903; Vigo Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Club Coruna;La Coruna;1904; Real Club Coruna');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Juventud Deportiva Gijonesa;Gijon;1904; Juventud Deportiva Gijonesa');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sport Club Avilesino;Aviles;1904; Sport Club Avilesino');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sporting Club Lucentino;Alicante;1904; Sporting Club Lucentino');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('San Sebastian Recreation Club;San Sebastian;1904; San Sebastian Recreation Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Gimnastico;Las Palmas;1904; Club Gimnastico');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Gran Canaria;Las Palmas;1904; Club Deportivo Gran Canaria');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Badajoz;Badajoz;1905;Badajoz');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('New Sporting Club;Madrid;1905; New Sporting Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Club Fortuna de Vigo;Vigo;1905; Real Club Fortuna de Vigo');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Foot-Ball Club Valencia;Valencia;1905; Foot-Ball Club Valencia');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Iris Foot-Ball Club;Madrid;1906; Iris Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Sportivo Internacional;Madrid;1906; Club Sportivo Internacional');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Espanol Foot-Ball Club;Madrid;1906; Espanol Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Tarrasa Futbol Club;Tarrasa;1906;Terrasa');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Sociedad Gimnastica Espanola;Madrid;1907; Real Sociedad Gimnastica Espanola');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Xerez Futbol Club;Jerez;1907; Xerez Futbol Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('San Sebastian Foot-Ball Club;San Sebastian;1908; San Sebastian Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Alicante Recreation Club;Alicante;1908; Alicante Recreation Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Gimnastico Foot-Ball Club;Valencia;1909; Gimnastico Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Foot-Ball Club Cabanal;Valencia;1907; Foot-Ball Club Cabanal');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Espanol Foot-Ball Club;Cadiz;1911; Espanol Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sporting Club;Vigo;1911; Sporting Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Vigo Sporting Club;Vigo;1911; Real Vigo Sporting Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Foot-Ball Club Malagueno;Malaga;1912; Foot-Ball Club Malagueno');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Norte;Tenerife;1912; Club Deportivo Norte');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Union Sporting Club;Madrid;1913; Union Sporting Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Nuevo Fomento Oriental;Las Palmas;1913; Club Nuevo Fomento Oriental');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Racing Club de Madrid;Madrid;1914; Racing Club de Madrid');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sestao Sport Club;Sestao;1916;Sestao');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Iberia Sport Club;Zaragoza;1916;Iberia');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Alicante Club de Futbol;Alicante;1918;Alicante');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Agrupacion Deportiva Ferroviaria;Madrid;1918;A.D. Ferroviaria');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Polideportivo Merida;Merida;1921;Merida');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Logrono;Logrono;1922;Logrono');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Burgos Club de Futbol;Burgos;1922;Burgos');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Imperio Club de Futbol;Madrid;1923;Imperio');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Union Deportiva Salamanca;Salamanca;1923;Salamanca');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club de Futbol Villarreal de Educacion y Descanso;Villarreal;1923;Villarreal E y D');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Nacional de Madrid;Madrid;1924;Nacional de Madrid');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club de Futbol Extremadura;Almendralejo;1924;Extremadura');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Getafe Foot-Ball Club;Getafe;1924; Getafe Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Zaragoza Club Deportivo;Zaragoza;1925; Zaragoza Club Deportivo');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Compostela Club de Futbol;Santiago;1928; Compostela Club de Futbol');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Club Deportivo Cordoba;Cordoba;1929; Real Club Deportivo Cordoba');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Castilla Foot-Ball Club;Madrid;1931; Castilla Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Malaga;Malaga;1933; Club Deportivo Malaga');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Condal;Barcelona;1934; Club Deportivo Condal');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Unio Esportiva Lleida;Lerida;1939;Lleida');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Logrones;Logrono;1940;Logrones');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Juvenil;La Coruna;1940; Club Deportivo Juvenil');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Eibar Foot-Ball Club;eibar;1940; Eibar Foot-Ball Club');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Getafe Deportivo;Getafe;1946; Club Getafe Deportivo');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Ourense;Orense;1952;Ourense');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('" Real Madrid Club de Futbol ""C""";Madrid;1952;Madrid C');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Sociedad Deportiva Compostela;Santiago;1962;Compostela');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('" Futbol Club Barcelona ""C""";Barcelona;1967;Barcelona C');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Polideportivo Ejido;El Ejido;1969;Ejido');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Agrupacion Deportiva Almeria;Almeria;1971;Almeria (A.D.)');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Merida Union Deportiva;Merida;1990;Merida');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Lorca Atletico Club de Futbol;Lorca;1996;Lorca');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Granada 74 Club de Futbol;Motril;1999;Granada 74');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Stadium Club Ovetense;Oviedo;1914; Real Stadium Club Ovetense');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Real Club Deportivo Oviedo;Oviedo;1919; Real Club Deportivo Oviedo');
INSERT INTO Equipo (Club, Ciudad, Fundacion, Nombre corto) VALUES ('Club Deportivo Espanol;Valladolid;1924; Club Deportivo Espanol');