INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nuevo Colombino','Rec. Huelva');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Ramon Sanchez Pizjuan','Sevilla');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('San Mames','Ath. Bilbao');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Camp Nou','Barcelona');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('RCDE Stadium','Espanyol');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Santiago Bernabeu','Real Madrid');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nova Creu Alta','Sabadell');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Municipal de Badalona','Badalona');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Metropolitano','At. Madrid');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nuevo Roman Suarez Puerta','Aviles');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('El Molinon','Sporting Gijon');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('La Mina','Carabanchel');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Riazor','Dptivo. Coruna');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nou Sardenya','Europa');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Benito Villamarin','Betis');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nuevo Malecon','Torrelavega');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nueva Condomina','Murcia');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Anoeta','Real Sociedad');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Ciudad de Valencia','Levante');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Camp Nou Municipal','Reus');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nuevo Mirador','Algeciras');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Ramon de Carranza','Cadiz');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Municipal','Linense');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Heliodoro Rodriguez Lopez','Tenerife');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('El Sardinero','Rac. Santander');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Artunduaga','Basconia');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('El Mazo','Haro');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nou Estadi de Tarragona','Gimn. Tarragona');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Jose Rico Perez','Hercules');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Stadium Gal','Real Union');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Son Moix','Mallorca');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Lasesarre','Barakaldo');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Hermanos Antuna','Caudal');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Cartagonova','Cartagena F.C.');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Municipal de Vilatenim','Figueres');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Principe Felipe','Cacereno');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Mestalla','Valencia');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('A Malata','Ferrol');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Balear','At. Baleares');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('El Sadar','Osasuna');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Pepico Amat','Eldense');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Mendizorroza','Alaves');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Castalia','Castellon');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('El Toralin','Ponferradina');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Manuel Martinez Valero','Elche');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Virgen de las Nieves','Tenisca');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nuevo Silvestre Carrillo','Mensajero');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Reino de Leon','Cult. Leonesa');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Balaidos','Celta');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Estadio de Vallecas','Rayo Vallecano');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Merkatondoa','Izarra');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Narcis Sala','Sant Andreu');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Carlos Tartiere','Oviedo');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Anduva','Mirandes');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Jose Zorrilla','Valladolid');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Butarque','Leganes');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Jose del Cuvillo','Portuense');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('La Victoria','Jaen');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Municipal de Montilivi','Girona');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Alfredo Di Stefano','Real Madrid B');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nuevo Los Carmenes','Granada');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Miramar','Luanco');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('La Romareda','Zaragoza');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Antonio Dominguez Alfonso','Marino');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Carlos Belmonte','Albacete');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Pasaron','Pontevedra');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Ipurua','Eibar');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nuevo Los Pajaritos','Numancia');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Estadio de la Ceramica','Villarreal');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Chapin','Xerez');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Pedro Escartin','Guadalajara');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Ciudad de Puertollano','Puertollano');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('La Rosaleda','Malaga (C.D.)');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Gran Canaria','Las Palmas');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Viejo Nervion','Sevilla B');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Angel Carro','Lugo');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nuevo Arcangel','Cordoba');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nou Municipal de Palamos','Palamos');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Alfonso Murube','Ceuta');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('El Alcoraz','Huesca');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Cerro del Espino​','At. Madrid B');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Las Gaunas','Logrones (U.D.)');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Mini Estadi','Barcelona B');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Santo Domingo','Alcorcon');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Municipal de Montilla','Montilla');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Cerro del Espino​','Rayo Majadahonda');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Coliseum Alfonso Perez','Getafe');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Juegos Mediterraneos','Almeria');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('El Plantio','Burgos (C.F.)');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Cartagonova','Cartagena');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Las Llanas','Sestao River');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('La Condomina','UCAM Murcia');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('San Lazaro','Compos');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Francisco de la Hera','Extremadura (U.D.)');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Las Gaunas','Logrones (S.D.)');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Olimpic de Terrassa','Tarrasa Olimpica');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Camp d Esports','Lleida Espiritu');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nuevo Vivero','Badajoz (C.D.)');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Chapin','Xerez (F.C.)');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Romano','Merida (A.D.)');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Rio Tinto');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Malaga English Clubn 7');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Athleta Club de Astilleros del Nervion');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Foot-Ball Club Barcelona');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Gran Canary Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Las Palmas Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Asociacion de Football de Torello');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Sociedad de Juegos al Aire Libre');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Hispania Athletic Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Retiro Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Hispania Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Victoria Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Union Vizcaina');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Universidad de Deusto Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Iberia Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Sport Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Internacional Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Boston Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Nacional Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Vizcaya Foot-Ball Clubn 8');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Malaga Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Club Foot-Ball Segoviano');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Asociacion Asturiana de Foot-Ball');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Oviedo Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Juventud Deportiva Gijonesa');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Sport Club Avilesino');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Nuevo Vivero','Badajoz');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','New Sporting Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Iris Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Club Sportivo Internacional');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Espanol Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Olimpic de Terrassa','Terrasa');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Club Deportivo Norte');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Club Nuevo Fomento Oriental');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Romano','Merida');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Las Gaunas','Logrono');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('El Plantio','Burgos');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Imperio');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Helmantico','Salamanca');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Estadio de la Ceramica','Villarreal E y D');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Nacional de Madrid');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Francisco de la Hera','Extremadura');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Getafe Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('La Rosaleda','Club Deportivo Malaga');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Camp d Esports','Lleida');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Las Gaunas','Logrones');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Riazor','Club Deportivo Juvenil');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Desconocido','Eibar Foot-Ball Club');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('O Couto','Ourense');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('San Lazaro','Compostela');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Mini Estadi','Barcelona C');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Santo Domingo','Ejido');
INSERT INTO Tener (Nom_Estadio,Nom_equip) VALUES ('Francisco Artes Carrasco','Lorca');
